SUPABASE_URL = "https://ztkxpouaswqlomjpjnwl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0a3hwb3Vhc3dxbG9tanBqbndsIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4NjkwNzMxMSwiZXhwIjoyMDAyNDgzMzExfQ.bZ8zRFn_6TD7bm0PzYcepIlhEDMkx78d0TGC5TuUFCM"
CHARGEPOINT_KEY = "8835549d1dc8d8e84dd4577073101bcd62bf62b90cfcf1656709817"
CHARGEPOINT_PASSWD = "d393decc21429c541086ed3f9010c721"
EMAIL = "nicholasmasri@gmail.com"
EMAIL_PASSWD = "txoavhivsjhrrhsl"